### ISSUE TITLE
Add "coding agent" type step

### ISSUE THREAD

**Issue by dersam** [Shopify/roast#141]
Right now when I want to call CodingAgent, I'm writing a prompt to "prompt CodingAgent to do X". I'm noticing some of my original instructions being dropped from the prompt created for CodingAgent, as the LLM doesn't include them in the prompt generated for the agent.

I'd like to have a step option for prompts that passes through the contents of `prompt.md` to a given coding agent or tool like Claude Code directly, so I don't have to introduce a translation step from another prompt.

Something like:

```yaml
steps:
  - my_prompt
      agent: claude
```

Or if we wanted something that could be generically used for any tool:
```yaml
steps:
  - my_prompt
      tool: coding_agent
        additional_param: something
        another_param: something_else
```
