### ISSUE TITLE
Remove test directory restriction from WriteFile tool, add function params

### ISSUE THREAD

**Issue by obie** [Shopify/roast#17]
At the moment, the WriteFile prevents writes except in the test/ directory, which is an unwanted carry-over from the original internal Shopify version when it was used specifically for writing tests. Remove this hard-coded restriction, but add the ability to pass arbitrary parameters to tool functions declaratively in the workflow.yml as a sibling to the `cached` function config.

```
functions:
  write_file:
    cached: true
    params:
      restrict: "test/
```
