### ISSUE TITLE
Create a Roast Tool for Swarm

### ISSUE THREAD

**Issue by obie** [Shopify/roast#182]
## Summary

Create a new Roast tool that integrates with [Claude Swarm](https://github.com/parruda/claude-swarm), allowing Roast workflows to leverage Swarm's multi-agent orchestration capabilities for Claude Code instances.

### Configuration
The Swarm tool should follow Roast's standard tool configuration patterns with multiple levels of configuration:

1. **Default Convention**: If no config is specified, look for Swarm configuration files in standard locations:
   - `claude-swarm.yml` in the current directory
   - `~/.claude-swarm.yml`
   
2. **Tool-level Configuration**: Specify a default config path in the `tools:` section that applies to all steps using this tool

3. **Step-level Configuration**: Override the swarm-config path for specific steps when different swarm configurations are needed

### Implementation Details
- Follow the pattern of existing Roast tools (e.g., `Roast::Tools::Cmd`)
- Implement `post_configuration_setup` method to handle tool-specific configuration
- Support configuration at both tool and step levels
- Since Claude Swarm is a Ruby gem, integration should be straightforward through Ruby's subprocess management

### Example Usage

```yaml
# Simple usage - looks for swarm config in default locations
tools:
  - Roast::Tools::Swarm

steps:
  - some_step_that_uses_a_swarm_of_agents
```

```yaml
# Tool-level configuration - all steps use this config by default
tools:
  - Roast::Tools::Swarm:
      config: "./custom/claude-swarm.yml"

steps:
  - research_task
  - write_task
```

```yaml
# Mixed configuration - tool default with step-level override
tools:
  - Roast::Tools::Swarm:

steps:
  - basic_step
  - specialized_task

specialized_workflow:
  swarm:
    config: "./specialized-swarm.yml"
```

### Technical Considerations
- The tool should integrate with Claude Swarm's Ruby API/CLI
- Use Ruby's subprocess management (e.g., `IO.popen`, `Open3`) to invoke Swarm commands
- Handle Swarm's agent orchestration results and make them available to subsequent steps
- Support passing context and variables between Roast and Swarm
- Consider whether to invoke Swarm as a subprocess or integrate it as a gem dependency
- Configuration precedence: step-level path > tool-level path > default locations

### Reference
- Claude Swarm: https://github.com/parruda/claude-swarm (Ruby gem for orchestrating Claude Code instances)
- See `Roast::Tools::Cmd` for configuration pattern example
- See MCP tool implementations for external integration patterns
