### ISSUE TITLE
Agent Step Not Working Properly

### ISSUE THREAD

**Issue by notImposterSyndromeIfImposter** [Shopify/roast#293]
## Problem Description

There are two related issues with agent steps (steps prefixed with `^`) in Roast:

1. **Agent steps fail with a NoMethodError** when trying to access step configuration
2. **Including `Roast::Tools::CodingAgent` in the tools section causes ALL steps to use Claude**, not just agent steps

### Without CodingAgent in tools:
```yaml
name: my_workflow
model: gpt-4o-mini

steps:
  - regular_step    # Uses gpt-4o-mini ✓
  - ^agent_step     # Fails with NoMethodError ✗
```

Error:
```
undefined method '[]' for nil (NoMethodError)
/lib/roast/workflow/agent_step.rb:16: step_config = workflow.config[name.to_s] || {}
```

### With CodingAgent in tools (assuming you fix 1):
```yaml
name: my_workflow
model: gpt-4o-mini

tools:
  - Roast::Tools::CodingAgent

steps:
  - regular_step    # Uses Claude (not gpt-4o-mini!) ✗
  - ^agent_step     # Uses Claude ✓
```

## Root Cause

1. **NoMethodError**: The `agent_step.rb` tries to access `workflow.config` which doesn't exist. It should use `workflow.workflow_configuration&.get_step_config(name.to_s)`.

2. **Model Override**: When `Roast::Tools::CodingAgent` is included in tools it routes ALL requests to Claude, regardless of the specified model.

# Getting Agent Step to run

### Fix the NoMethodError in agent_step.rb

```diff
# lib/roast/workflow/agent_step.rb:16
- step_config = workflow.config[name.to_s] || {}
+ step_config = workflow.workflow_configuration&.get_step_config(name.to_s) || {}
```

### Get agent step to work AND override settings with this workaround:

Don't include `CodingAgent` in tools. Instead, configure it via:

**Environment variable:**
```bash
export CLAUDE_CODE_COMMAND="claude --model opus -p --allowedTools 'Bash, Glob, Grep'"
```

## Expected Behavior After Fix

```yaml
name: my_workflow
model: gpt-4o-mini

# NO CodingAgent in tools!
steps:
  - regular_step    # Uses gpt-4o-mini ✓
  - ^agent_step     # Uses Claude (configured via env/initializer) ✓
```

## Steps to Reproduce

1. Create a workflow with both regular and agent steps
2. Set model to `gpt-4o-mini`
3. Try running without `CodingAgent` in tools (agent step fails)
4. Add `CodingAgent` to tools (all steps use Claude)
5. Apply the fix and use env variable instead (works correctly)

## Environment

- Roast version: 0.4.2
- Ruby version: 3.4.2
