### ISSUE TITLE
Implement Conditional Execution (if/unless) for Workflows

### ISSUE THREAD

**Issue by obie** [Shopify/roast#47]
# Conditional Execution (if/unless) for Workflows

## Background

Workflow steps often need to execute conditionally based on the output of previous steps, file status, or other criteria. The current workflow structure doesn't support direct conditional branching, making it impossible to create dynamic workflows that respond to runtime conditions.

## Proposed Solution

Implement conditional step execution allowing workflows to run steps based on conditions:

```yaml
steps:
  - check_requirements
  - 
    if: "{{output.check_requirements.success}}"
    then:
      - run_main_process
    else:
      - handle_missing_requirements
  
  # OR using unless (inverse condition)
  - 
    unless: "{{File.exist?(output_file)}}"
    then:
      - generate_output_file
```

## Implementation Details

1. **Expression Evaluation**
   - Reuse existing Ruby expression evaluator to process condition strings within workflow context (similar to each iterator)

2. **Workflow Structure**
   - Add JSON schema validation for 'if/unless' conditional structures
   - Support both 'then' and 'else' branches for complete branching
   - Allow nesting of conditional blocks for complex logic

3. **Execution Flow**
   - Modify workflow executor to evaluate condition before step execution
   - Track condition results for debugging and state management
   - Ensure consistent session state persistence for each execution path

4. **Error Handling**
   - Add clear error reporting for expression evaluation failures
   - Validate conditional structure at workflow load time
   - Provide debugging tools for condition evaluation issues

## Technical Approach

1. Extend the workflow configuration schema to support conditionals
2. Create a condition evaluator for processing expressions
3. Modify the workflow executor to handle conditional branching
4. Add support for condition tracking in the state repository
5. Implement comprehensive error handling and reporting

## Acceptance Criteria

- [x] Workflow YAML can include if/unless conditionals
- [x] Conditions can reference previous step outputs, files, or environment
- [x] Both 'then' and 'else' branches are properly executed based on conditions
- [x] Failed condition evaluations produce clear error messages
- [x] Session replay properly restores conditional execution paths
- [x] Documentation and examples demonstrate conditional usage patterns

## Related Issues

Parent Epic: #46 Enhanced Control Flow for Roast Workflows
