### ISSUE TITLE
Implement Iteration Mechanisms for Workflows

### ISSUE THREAD

**Issue by obie** [Shopify/roast#48]
# Iteration Mechanisms for Workflows

## Background

Many workflow automation scenarios require processing collections of items or repeating operations until a condition is met. Currently, Roast doesn't support iterative execution, forcing users to create separate workflows or inefficient workarounds for repetitive tasks.

## Proposed Solution

Implement loop constructs to support both conditional repetition and collection iteration:

### Repeat Until Pattern

```yaml
steps:
  - prepare_data
  - repeat:
      steps:
        - process_batch
        - validate_results
      until: "{{output.validate_results.complete == true}}"
      max_iterations: 10  # Safety limit
```

### Collection Iteration Pattern

```yaml
steps:
  - get_file_list
  - each: "{{output.get_file_list.files}}"
    as: "current_file"
    steps:
      - analyze_file  # Can access {{current_file}}
      - generate_report
```

## Implementation Details

1. **Loop State Management**
   - Track iteration count and loop variables
   - Support breaking out of loops early based on conditions
   - Handle loop variable scoping correctly

2. **Collection Processing**
   - Support iteration over arrays, hashes, and other enumerable objects
   - Pass current iteration value as a variable to nested steps
   - Allow nested iterations for complex processing

3. **Safety Mechanisms**
   - Implement maximum iteration limits to prevent infinite loops
   - Add timeout options for long-running iterations
   - Provide circuit breakers for error handling

4. **Performance Considerations**
   - Optimize state persistence for loop execution
   - Allow parallel execution of iterations where applicable
   - Consider memory usage for large collections

## Technical Approach

1. Extend workflow configuration schema to support loop structures
2. Create an iteration controller to manage loop execution
3. Implement variable scope management for loop contexts
4. Add state tracking for loop progress and resumption
5. Develop safety mechanisms to prevent runaway loops

## Acceptance Criteria

- [ ] Workflows can repeat steps until a condition is met
- [ ] Workflows can iterate over collections (arrays, hashes)
- [ ] Loop variables are properly scoped and accessible in steps
- [ ] Maximum iteration limits prevent infinite loops
- [ ] Loop state is properly persisted for resumption after failure
- [ ] Iteration can handle nested loops and complex structures
- [ ] Documentation and examples demonstrate various iteration patterns

## Related Issues

Parent Epic: #46 Enhanced Control Flow for Roast Workflows
