### ISSUE TITLE
Implement Early Exit and Skip Controls for Workflows

### ISSUE THREAD

**Issue by obie** [Shopify/roast#49]
# Early Exit and Skip Controls for Workflows

## Background

Workflows sometimes need to terminate early or skip certain steps based on runtime conditions. Currently, there's no way to exit a workflow early or conditionally skip sections without complex workarounds, leading to inefficient execution paths and unnecessary processing.

## Proposed Solution

Implement early exit and skip mechanisms to provide more control over workflow execution:

### Early Exit Pattern

```yaml
steps:
  - validate_input
  - 
    exit_if: "{{output.validate_input.fatal_error}}"
    message: "Terminating workflow due to fatal input error"
  - process_data
```

### Skip Steps Pattern

```yaml
steps:
  - process_data
  - 
    skip_if: "{{output.process_data.no_results}}"
    steps:
      - generate_visuals
      - create_dashboard
```

## Implementation Details

1. **Exit Control**
   - Add support for early workflow termination with status message
   - Allow customizable exit codes/status for integration with other systems
   - Ensure proper cleanup and state finalization on early exit

2. **Skip Control**
   - Implement conditional skipping of step groups
   - Maintain workflow state consistency when steps are skipped
   - Support clear logging of skipped steps for debugging

3. **Integration with State Management**
   - Record exit reasons and skip decisions in workflow state
   - Ensure state repository properly handles early termination
   - Support resumption that respects previous skip/exit decisions

4. **Workflow Validation**
   - Validate that exit/skip conditions can be properly evaluated
   - Check for proper step structure in skip blocks
   - Ensure message templates are valid

## Technical Approach

1. Extend workflow configuration schema to support exit_if and skip_if structures
2. Modify workflow executor to handle early termination and step skipping
3. Update state persistence to record skip/exit decisions
4. Implement clear logging and reporting for skipped steps and early exits
5. Ensure schema validation for new control structures

## Acceptance Criteria

- [x] Workflows can exit early based on conditions
- [x] Exit status/message is properly recorded and reported
- [x] Groups of steps can be conditionally skipped
- [x] Skip/exit decisions are logged clearly for debugging
- [x] State repository correctly handles early termination
- [x] Session replay respects previous skip/exit decisions
- [x] Documentation and examples demonstrate skip/exit usage patterns

## Related Issues

Parent Epic: #46 Enhanced Control Flow for Roast Workflows

**Comment by xrendan** [comment]
This would be nicer and more extensible if instead we implemented an if


 ### Early Exit Pattern
 ```yaml
 steps:
   - validate_input
   - 
     if: "{{output.validate_input.fatal_error}}"
     steps: 
       - exit! "Terminating workflow due to fatal input error"
   - process_data
 ```
 ### Skip Steps Pattern
 
```yaml
 steps:
   - process_data
   - 
     if: "{{output.process_data.no_results}}"
     steps:
       - generate_visuals
       - create_dashboard
```
