### ISSUE TITLE
Implement Dynamic Step Selection (case/when/else) for Workflows

### ISSUE THREAD

**Issue by obie** [Shopify/roast#50]
## Description

Implement a dynamic step selection mechanism (similar to Ruby's case/when/else statements) for Roast workflows to allow for branching between multiple execution paths based on a condition's value.

## Problem

Currently, Roast workflows execute steps in a linear sequence without the ability to dynamically select between multiple different execution paths based on a condition's value. This makes it difficult to create workflows that need to perform different operations based on specific conditions.

## Proposed Solution

Implement a `case` control flow mechanism that allows workflows to evaluate an expression and execute different steps based on the value:

```yaml
steps:
  - name: determine_file_type
    prompt: determine_file_type/prompt.md
    output: file_type
  
  - case: "{{ workflow.output.file_type }}"
    when:
      ruby:
        - name: process_ruby
          prompt: process_ruby/prompt.md
      javascript:
        - name: process_javascript
          prompt: process_javascript/prompt.md
      python:
        - name: process_python
          prompt: process_python/prompt.md
    else:
      - name: process_unknown
        prompt: process_unknown/prompt.md
```

## Implementation Details

1. Extend the workflow schema to support the `case/when/else` control structure
2. Update the workflow executor to handle case/when logic
3. Implement expression evaluation for determining which when clause to execute
4. Support an else clause for when no matches are found
5. Allow nested steps within each when clause
6. Update the documentation to explain the new functionality

## Acceptance Criteria

- [ ] Workflow schema supports the `case/when/else` control structure
- [ ] Workflow executor correctly evaluates expressions and executes the appropriate when clause
- [ ] Multiple steps can be nested within each when block
- [ ] Else clause executes when no other when clauses match
- [ ] Comprehensive tests cover all edge cases (no matches, invalid expressions, etc.)
- [ ] Documentation is updated with examples

## Related Issues

Part of #46 (Enhanced Control Flow for Roast Workflows)
