### ISSUE TITLE
Pre/Post Processing Framework for Multi-Target Workflows

### ISSUE THREAD

**Issue by obie** [Shopify/roast#61]
## Description

This epic introduces a convention-oriented framework for executing pre- and post-processing steps in Roast workflows that operate on multiple targets.

### Overview

We propose adding two new phases to multi-target workflows:
- **Pre-processing**: Steps executed once before any targets are processed
- **Post-processing**: Steps executed once after all targets have been processed

This enhancement will enable workflows to perform setup tasks, aggregate results, and generate comprehensive reports across all processed targets.

### Implementation Details

1. **Configuration**:
   ```yaml
   # Example workflow.yml
   name: optimize_tests
   model: gpt-4o
   
   pre_processing:
     - setup_environment
     - gather_initial_metrics
   
   steps:
     - analyze_test
     - improve_test_coverage
     - validate_changes
   
   post_processing:
     - aggregate_results
     - generate_report
   ```

2. **Convention-based File Structure**:
   ```
   workflow.yml
   pre_processing/
     ├── setup_environment/
     │   └── prompt.md
     └── gather_initial_metrics/
         └── prompt.md
   steps/
     ├── analyze_test/
     │   └── prompt.md
     └── ...
   post_processing/
     ├── aggregate_results/
     │   └── prompt.md
     └── generate_report/
         └── prompt.md
   ```

3. **Results Processing Template**:
   - Add support for a special `results_template.erb` file that defines how to transform workflow outputs into a structured format for post-processing
   - This template would have access to all workflow results and transcripts

4. **Context Sharing**:
   - Pre-processing steps share context with the main workflow
   - Post-processing steps have access to:
     - All target outputs
     - Aggregated metrics
     - Pre-processing results

### Example Use Cases

1. **Test Optimization Reporting**:
   - Pre-processing: Establish baseline metrics (coverage, test count)
   - Workflow: Optimize individual test files
   - Post-processing: Generate report showing:
     - Number of tests modified
     - Total coverage increase
     - Performance improvements

2. **Codebase Migration**:
   - Pre-processing: Analyze dependencies, create migration plan
   - Workflow: Update individual files
   - Post-processing: Compile migration report, identify remaining issues

3. **Content Generation**:
   - Pre-processing: Define style guide, establish context
   - Workflow: Generate individual content pieces
   - Post-processing: Create table of contents, ensure consistency

### Technical Considerations

- Post-processing should be able to access a structured representation of all workflow outputs
- Pre-processing results should be available to all workflow steps
- Should work seamlessly with the existing session replay functionality
- Should provide appropriate error handling if pre-processing fails

This enhancement builds on Roast's convention-over-configuration philosophy while adding powerful new capabilities for multi-target workflows.
