### ISSUE TITLE
Add Dot Notation Access for Output Hash in Workflow Configurations

### ISSUE THREAD

**Issue by obie** [Shopify/roast#63]
## Description

Currently, accessing nested values in the workflow output hash requires using bracket notation with string keys:

```yaml
until: "output['update_fix_count']['fixes_applied'] >= 5 || output['select_next_issue']['no_issues_left'] == true"
```

This syntax becomes verbose and error-prone as nesting levels increase. We should introduce a more elegant dot notation access pattern that simplifies these expressions:

```yaml
until: "output.update_fix_count.fixes_applied >= 5 || output.select_next_issue.no_issues_left == true"
```

## Implementation Details

1. **Create a wrapper class** around the output hash that:
   - Maintains compatibility with the existing hash access pattern
   - Provides method_missing implementation to support dot notation
   - Automatically converts nested hashes to the same wrapper class
   - Handles nil values gracefully to prevent NoMethodError exceptions

2. **Replace direct hash access** in workflow execution with the wrapper:
   ```ruby
   # Before
   workflow.output = {}
   
   # After
   workflow.output = DotAccessHash.new({})
   ```

3. **Ensure serialization compatibility** so that the wrapper:
   - Can be properly serialized when saving session state
   - Maintains dot notation access when deserializing

## Benefits

- **Improved readability**: Expressions in workflow YAML become more concise and intuitive
- **Reduced errors**: Less chance of typos in string keys or missing quotes
- **Better IDE support**: Most editors provide better autocomplete for dot notation than bracket notation
- **Consistency**: Aligns with modern Ruby SDK patterns found in libraries like Stripe

## Considerations

- Ensure backward compatibility with existing workflows using bracket notation
- Address edge cases where key names contain special characters or match existing method names
- Add thorough documentation and examples of the new syntax
- Consider adding proper type conversion for common value types (e.g., booleans, numbers)

## Example Usage

```yaml
# Current syntax
if: "output['analysis']['complexity_score'] > 10"
until: "output['processed_count'] >= output['total_files']"

# New dot notation
if: "output.analysis.complexity_score > 10"
until: "output.processed_count >= output.total_files"
```
